### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/hide-files-on-github#2]
Should be possible to edit the rules for what files/folder to hide using regex patterns. Saved in localStorage so they're synced.

Need an option page for this: https://github.com/roykolak/chrome-bootstrap

**Comment by radiovisual** [comment]
@sindresorhus , I have an [options branch on my fork](https://github.com/radiovisual/hide-files-on-github/tree/options) that features a new options page. The options page I built has the ability to dim files instead of hide them (#3), and add an optional regular expression to ignore specific files. 

Here is a screenshot of my options page (uses chrome bootstrap):

![hfog-options-screenshot](https://cloud.githubusercontent.com/assets/5614571/12115965/242fe190-b3ae-11e5-9b71-ae0dde6e3613.png)

Everything seems to work, but I am going to play with a little more and see if I can fuzz out any hidden issues, and maybe refactor a smidge. :cake:

**Comment by sindresorhus** [comment]
Looks good :)
