### ISSUE TITLE
Collapse all hidden files to a single item in the list.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/hide-files-on-github#33]
Rather than the button to show files, what about creating a single expando entry in the list saying "hidden files". It's a gentle reminder that you aren't seeing all the files, and you would find it more intuitively when you've forgotten this extension is installed and are searching for `.gitignore` in response to some unexpected file making it into a PR.

**Comment by sindresorhus** [comment]
Something like this, right?

<img width="569" alt="screen shot 2016-05-18 at 11 33 46" src="https://cloud.githubusercontent.com/assets/170270/15347494/6b372cfe-1cec-11e6-902d-5adf3bb13b6f.png">

**Comment by jamestalmage** [comment]
Yep!

Maybe a little more obvious in the styling that it's different from the rest (and expandable). maybe just a `...` like next to the commit message.

**Comment by sindresorhus** [comment]
Agreed. PR welcome. (Maybe @radiovisual or @acobbearden would be interested).

**Comment by radiovisual** [comment]
I like this idea. Something like this is more likely to persist against github's frequent UI updates to the File Navigation Bar.

I don't mind taking this on, so it's just a matter of deciding where we want to the injected 'expando' link to go. @jamestalmage suggested an ellipses `...` next to the commit message, but github already does that (as you can see in @sindresorhus 's screenshot above: there is already an ellipses to right of the commit message which encapsulates the merged PR's various commit messages). So my vote is to put the expando link either at the bottom of the file table (like in sindre's screenshot) or at the top of the file table so that it's immediately obvious if you have the hidden files hidden or shown.

**Comment by jamestalmage** [comment]
I was suggesting it be similar to the ellipse next to the commit message, not that it should be the location.

Bottom or top. Not sure which would be better.

**Comment by radiovisual** [comment]
Oh I see. Sorry I misunderstood. 

I already started implementing the functionality in PR #34 which puts the button at the bottom (the bottom felt a bit more natural to me), but as for the position and styling of the button, I am totally open to suggestions.
