### ISSUE TITLE
Feature request: Hide files in PRs/Commit views

### ISSUE THREAD

**Issue by hiradyazdan** [sindresorhus/hide-files-on-github#80]
When there are loads of non-reviewable files (e.g. *.meta and binary files) in PRs or commit views and the reviewer don't want to scroll 100 times to reach to the block they're looking for, having the ability to hide/collapse certain files by their extensions would be quite useful in the browser.

I presume this is a semi-controversial feature request, as so many Pull requests and issues rejected this request in [refined-github](https://github.com/sindresorhus/refined-github) repo. 

However, I can't see why this won't fit in this repository and I haven't found any other issue or PR being rejected here.

Also, I found no other extension implementing this feature for Github (there's one for BitBucket only), and since both [refined-github](https://github.com/sindresorhus/refined-github) and [hides-files-on-github](https://github.com/sindresorhus/hide-files-on-github) are to me the best extension for these scenarios, I struggle to understand why this feature cannot still exist in any of them. 

So, here's me giving it a try here. Please try to keep an open mind on this request :)

**Comment by sindresorhus** [comment]
> having the ability to hide/collapse certain files by their extensions would be quite useful in the browser.

You can already do this natively: https://help.github.com/en/articles/filtering-files-in-a-pull-request-by-file-type

---

And if you want to permanently collapse certain file types for all users of a repo, you can mark certain file types as vendored or generated to have them be collapsed in the PR diff: https://github.com/github/linguist#vendored-code

**Comment by hiradyazdan** [comment]
@sindresorhus I wasn't aware of this. Thanks! How about commit views on their own? I don't see any filter by default. Can this be implemented in this repository?

**Comment by sindresorhus** [comment]
> How about commit views on their own?

I see it: https://github.com/sindresorhus/refined-github/pull/2073/commits/943f7a788383b5d15ba54185d3ea463fe4fc25f7

**Comment by sindresorhus** [comment]
Even if there was something missing natively, I'm not really interested in it as it doesn't solve a problem I have.

**Comment by hiradyazdan** [comment]
This is not same as hiding however, and it still with large number of files, is still an issue to me. But sounds like it's not to you. Anyway, I tried :)

**Comment by OmarJaroudi** [comment]
Have there been any updates regarding this issue? I'm working with a Unity project and every PR contains a huge amount of files, when in fact I would only like for *.cs files to appear as changed, because they are the actual files I am working on locally. Everything else is auto-generated. Again, collapsing a file doesn't change the fact that it still shows up in the PR.

**Comment by KevinGelkingSviper** [comment]
We recently switched from Bitbucket to GitHub and very dearly miss the option to hide / exclude certain types from showing up at all. Our PRs often contain a very (!) large number of files due to generated assets for an area with a few script files inbetween.

The problem is that on GitHub you cannot set the project itself to hide .meta and .asset etc by default, which causes the GitHub PR page to Unicorn out due to failing to load all those files.

![image](https://user-images.githubusercontent.com/103119563/186866493-346d542e-c02c-467f-bb22-b7248d4fbb3a.png)

Sure, in many cases every single time someone creates a PR every reviewer can go into the file view and untick all file types over and over PR for PR; but in my opinion that is not at all a solution to the problem of them being shown by default.
